export const siteConfig = {
  name: "Shivam Gaur",
  title: "Shivam Gaur | Full Stack Developer | MERN Stack | Portfolio",
  description:
    "Shivam Gaur is a Full Stack Developer specializing in React, Next.js, Node.js, and MongoDB. Based in NOIDA, India. Explore projects, experience, and resume.",
  url: process.env.NEXT_PUBLIC_BASE_URL || "https://shivamgaur.space",
  ogImage: `${process.env.NEXT_PUBLIC_BASE_URL || "https://shivamgaur.space"}/og-home.png`,
  ogImages: {
    home: `${process.env.NEXT_PUBLIC_BASE_URL || "https://shivamgaur.space"}/og-home.png`,
    resume: `${process.env.NEXT_PUBLIC_BASE_URL || "https://shivamgaur.space"}/og-resume.png`,
    experience: `${process.env.NEXT_PUBLIC_BASE_URL || "https://shivamgaur.space"}/og-experience.png`,
    projects: `${process.env.NEXT_PUBLIC_BASE_URL || "https://shivamgaur.space"}/og-projects.png`,
    oneHundredList: `${process.env.NEXT_PUBLIC_BASE_URL || "https://shivamgaur.space"}/og-100-list.png`,
    movies: `${process.env.NEXT_PUBLIC_BASE_URL || "https://shivamgaur.space"}/og-movies.png`,
  },
  links: {
    twitter: "https://twitter.com/ishivamgaur",
    github: "https://github.com/ishivamgaur",
    linkedin: "https://linkedin.com/in/ishivamgaur",
    instagram: "https://instagram.com/ishivamgaur",
  },
  keywords: [
    // Name variations
    "Shivam Gaur",
    "Shivam",
    "shivam developer",
    "shivam gaur developer",
    "shivam web developer",
    "shivam full stack",
    "shivam react js",
    "shivam next js",
    "shivam mern",
    "shivam noida",
    "shivam software engineer",
    "shivam frontend",
    "shivam backend",
    "shivam coder",
    "portfolio shivam",
    "shivam tech portfolio",
    "hire shivam",
    "ishivamgaur",
    "ishivamgaur developer",
    "ishivamgaur portfolio",
    "ishivamgaur projects",
    "ishivamgaur resume",
    "Shivam Gaur Portfolio",
    "Shivam Gaur personal website",
    "Shivam Gaur developer portfolio",
    "shivam gaur portfolio website",
    "ishivamgaur portfolio website",
    "shivam developer portfolio",
    "portfolio shivam gaur",
    "shivam gaur official site",
    "shivam gaur official website",
    "ishivamgaur official website",
    "shivam gaur online portfolio",
    "hire shivam gaur",
    "shivam gaur contact",
    "shivam gaur bitmax",
    "shivam gaur digivity",
    "shivam gaur mern",
    "shivam gaur react js",
    "Shivam Gaur Resume",
    "Shivam Gaur Developer",
    "Shivam Gaur Software Engineer",
    "Shivam Gaur Full Stack",
    "Shivam Gaur GitHub",
    "Shivam Gaur LinkedIn",
    // Role keywords
    "Full Stack Developer",
    "Full Stack Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "MERN Stack Developer",
    "Software Developer",
    "Software Engineer",
    "Web Developer",
    "React Developer",
    "Next.js Developer",
    "Node.js Developer",
    "JavaScript Developer",
    "TypeScript Developer",
    "MongoDB Developer",
    "Express.js Developer",
    // Tech stack
    "React.js",
    "Next.js",
    "Node.js",
    "MongoDB",
    "Express.js",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "Redux",
    "AWS",
    "REST API",
    "MERN Stack",
    // Location-based
    "Developer NOIDA",
    "Developer Greater Noida",
    "Web Developer NOIDA",
    "Software Developer India",
    "Full Stack Developer India",
    "Full Stack Developer NOIDA",
    "Full Stack Developer Greater Noida",
    "Software Engineer India",
    "Freelance Developer India",
    // Hiring / intent-based
    "hire full stack developer",
    "hire react developer",
    "hire MERN developer India",
    "developer portfolio website",
    "software developer portfolio",
    "best full stack developer portfolio",
    "noida based software engineer",
    "freelance web developer noida",
    "creative developer portfolio",
    "modern web developer portfolio",
  ],
  author: "Shivam Gaur",
  creator: "Shivam Gaur",
};

export type SiteConfig = typeof siteConfig;
